services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: salon
      POSTGRES_PASSWORD: salonpass
      POSTGRES_DB: salon_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    depends_on:
      - db
    volumes:
      - ./app:/app
    environment:
      DATABASE_URL: postgresql://salon:rQ750VVDxHgEgSazxzTyVsdbtz4mUuB8@dpg-d68r1ji48b3s73aqbpeg-a.oregon-postgres.render.com/salonbooking_db
      SECRET_KEY: c48e4acb9d22794bd03e3f0e3b1eaf82afb35a72f8ec0ec09947eb7755c57f40
      ACCESS_TOKEN_EXPIRE_MINUTES: "30"
    ports:
      - "8000:8000"

volumes:
  pgdata:
